default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: store_stock_api_development

test:
  <<: *default
  database: store_stock_api_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV["STORE_STOCK_API_DATABASE_NAME"] || "store_stock_api_production" %>
  username: <%= ENV["STORE_STOCK_API_DATABASE_USERNAME"] %>
  password: <%= ENV["STORE_STOCK_API_DATABASE_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] %>
